### ISSUE TITLE
When will the code be released？

### ISSUE THREAD

**Issue by Yu-Jiawei** [runnanchen/CLIP2Scene#1]
Thank you for this excellent work, but when will you please public the code?

**Comment by shenxiaowrj** [comment]
+1

**Comment by runnanchen** [comment]
Thanks for your attention. We are reorganizing and cleaning up the code, and will release the code in this month.

**Comment by guwen007** [comment]
> Thanks for your attention. We are reorganizing and cleaning up the code, and will release the code in this month.
thank you, waiting for your code ！

**Comment by guwen007** [comment]
thank you, waiting for your code ！

**Comment by chanhoeom** [comment]
Awesome :) I'm waiting for the code too

**Comment by gbliao** [comment]
+1
