### ISSUE TITLE
How to obtain the ‘ViT16_clip_weights.pth’ ?

### ISSUE THREAD

**Issue by jijun-cheng** [runnanchen/CLIP2Scene#3]
Thank you for this excellent work.

When I pre-training `python pretrain.py --cfg_file config/clip2scene_nuscenes_pretrain.yaml` , the following error is reported. 

`FileNotFoundError: [Errno 2] No such file or directory: '/nvme/konglingdong/runnan/CLIP2Scene/ViT16_clip_weights.pth'
`

How can I obtain the  file `ViT16_clip_weights.pth'`?

**Comment by chenhaomingbob** [comment]
I meet the same problem.

**Comment by runnanchen** [comment]
Please refer to step 3. of Data Preparation. Thanks!
